services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis-geography:5432/${POSTGRES_DB}
    networks:
      - db-net
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  db-net:
    external: true
