"""Add international and short names

Revision ID: 1bb3ee2beeca
Revises: 5e46f949ca38
Create Date: 2026-05-28 08:19:05.889292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb3ee2beeca'
down_revision: Union[str, Sequence[str], None] = '5e46f949ca38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('international_name', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('short_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'short_name')
    op.drop_column('businesses', 'international_name')
    # ### end Alembic commands ###
